language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  global:
    CC_TEST_REPORTER_ID=$code_climate_token

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm install   # Install npm dependencies

# Run the test suites
script:
  - npm test -- --coverage

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
